services:
  db:
    image: postgres
    container_name: ontapapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./beers_db.backup:/bkp/beers_db.backup
    networks:
      - ontapapp-net

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ElasticApm__LogLevel=Debug
    volumes:
      - ../OnTapApp.API:/src/OnTapApp.API
      - ~/.vsdbg:/remote_debugger:rw

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ElasticApm__LogLevel=Debug
    volumes:
      - ../OnTapApp.Web:/src/OnTapApp.Web

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: ontapapp-pgweb
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8085:8081"
    depends_on:
      - db
    networks:
      - ontapapp-net